### ISSUE TITLE
Missing environment variables in docker-compose

### ISSUE THREAD

**Issue by CubexsOne** [PythBuster/savings_manager#96]
There are some missing environment variables in the docker-compose.yaml

- ENVIRONMENT
- SMTP_SERVER
- SMTP_PORT
- SMTP_METHOD
- SMTP_USER_NAME
- SMTP_PASSWORD

And `ENVIRONMENT` needs a value like `test` or `prod`

**Comment by PythBuster** [comment]
Updated description in README.md.
